:toc:
:toclevels: 2

= Циклы

== Задача 1. Вывод чисел от 1 до 10

Напишите программу, которая выводит числа от 1 до 10 с использованием цикла `while`. Убедитесь, что цикл гарантированно выполняется хотя бы один раз.

Пример вывода:
```python
1
2
3
...
10
```

== Задача 2. Ввод числа больше 100 

Напишите программу, которая запрашивает у пользователя число больше 100. В цикле `while` программа должна выполнять проверку, корректное ли число ввел пользователь. 
* Если число не удовлетворяет требованиям, выполняется повторная итерациядолжна. 
* Если число удовлетворяет требованиям, программа завершается.

Пример работы программы:

```python
Введите число больше 100: 50
Введите число больше 100: 99
Введите число больше 100: 150
```

== Задача 3. Сумма введённых чисел

Напишите программу, которая запрашивает у пользователя ввод целых чисел, пока не будет введено отрицательное число. Программа должна подсчитывать и выводить сумму всех введённых положительных чисел.

Пример работы программы:

```python
Введите число: 10
Введите число: 5
Введите число: 20
Введите число: -1
Сумма положительных чисел: 35
```

== Задача 4. Угадай число 

Реализуйте игру, в которой программа загадывает случайное число от 1 до 50, а пользователь должен угадать это число. 
Программа должна давать подсказки: "больше" или "меньше", и продолжать цикл до тех пор, пока пользователь не угадает число.

NOTE: Для генерации случейных чисел используется функция `randint()` из модуля `random`. 
```python
import random
# Генерируем случайное число в диапазоне от 1 до 10 (включительно)
random_number = random.randint(1, 10)
```

== Задача 5.  Сумма чисел от 1 до N 

Напишите программу, которая запрашивает у пользователя число N и с помощью цикла `for` находит сумму всех чисел от 1 до N.

Пример работы программы:
```python
Введите число: 5
Сумма чисел от 1 до 5: 15
```

== Задача 6. Вывод каждого символа строки 

Напишите программу, которая принимает строку от пользователя и выводит каждый символ строки на новой строке с помощью цикла `for`.

NOTE: str in string

Пример работы программы:
```python
Введите строку: Hello
H
e
l
l
o
```

== Задача 7. Факториал числа 

Напишите программу, которая с помощью цикла `for` находит факториал числа `N`, введённого пользователем. (Факториал числа `N` — это произведение всех чисел от 1 до N, обозначается как N!).

Пример работы программы:
```python
Введите число: 5
Факториал числа 5: 120
```

== Задача 8. Четные числа
Напишите программу, где пользоавтель вводит левую и правую границы диапазона.
Результатом программы служит вывод всех четных чисел из заданного диапазона с помощью цикла for.

Пример работы программы:
```python
Input: start = 4, end = 15
Output: 4, 6, 8, 10, 12, 14

Input: start = 8, end = 11
Output: 8, 10
```